%% ============================================================
%  STM32 + ESP-01 REALTIME MOTOR MONITOR
%  MATLAB R2020b
%
%  Data format:
%  Boot : Mode:X,ADC:XXXX,Duty:XX.X,Pos:XX.XX,RPM:XX.XX
%
%  Mode:
%       0 = FORWARD
%       1 = REVERSE
%       2 = STOP
%% ============================================================

delete(instrfindall);
clear;
close all;
clc;

%% ============================================================
%                       CONFIG
%% ============================================================

SERVER_IP   = '172.20.10.7';
SERVER_PORT = 8000;

ESP_IP      = '172.20.10.12';

TIMEOUT     = 120;

PLOT_WINDOW = 30;      % do thi hien thi 30 giay gan nhat
MAX_POINTS  = 500;     % so diem toi da trong animatedline

DATA_TIMEOUT = 3.0;    % qua 3s khong co packet -> DATA LOST

mode_names = {'FORWARD', 'REVERSE', 'STOP'};

%% ============================================================
%                       TCP SERVER
%% ============================================================

server = tcpip( ...
    '0.0.0.0', ...
    SERVER_PORT, ...
    'NetworkRole', 'server');

server.Timeout = TIMEOUT;
server.InputBufferSize = 4096;

%% ============================================================
%                       GUI
%% ============================================================

fig = figure( ...
    'Name', 'STM32 Motor Control System', ...
    'NumberTitle', 'off', ...
    'Position', [40 40 1450 850], ...
    'Color', [0.06 0.07 0.09], ...
    'MenuBar', 'none', ...
    'ToolBar', 'none', ...
    'Resize', 'on');

setappdata(fig, 'STOP_PROGRAM', false);

fig.CloseRequestFcn = @(src,event) ...
    setappdata(src, 'STOP_PROGRAM', true);

%% ============================================================
%                       TITLE
%% ============================================================

uicontrol(fig, ...
    'Style', 'text', ...
    'String', 'STM32 MOTOR CONTROL SYSTEM', ...
    'Units', 'normalized', ...
    'Position', [0.02 0.945 0.96 0.045], ...
    'FontSize', 21, ...
    'FontWeight', 'bold', ...
    'ForegroundColor', [0.25 0.80 1.00], ...
    'BackgroundColor', [0.06 0.07 0.09]);

%% ============================================================
%                    MAIN CONNECTION BAR
%% ============================================================

statusText = uicontrol(fig, ...
    'Style', 'text', ...
    'String', sprintf( ...
    'WAITING FOR ESP-01 CONNECTION  |  SERVER %s:%d', ...
    SERVER_IP, SERVER_PORT), ...
    'Units', 'normalized', ...
    'Position', [0.02 0.900 0.96 0.035], ...
    'FontSize', 11, ...
    'FontWeight', 'bold', ...
    'ForegroundColor', [1.00 0.75 0.20], ...
    'BackgroundColor', [0.11 0.12 0.15]);

%% ============================================================
%                       VALUE CARDS
%% ============================================================

%% ---------------- MODE ----------------

panelMode = uipanel(fig, ...
    'Units', 'normalized', ...
    'Position', [0.02 0.765 0.18 0.11], ...
    'BackgroundColor', [0.11 0.12 0.15]);

uicontrol(panelMode, ...
    'Style', 'text', ...
    'String', 'MOTOR MODE', ...
    'Units', 'normalized', ...
    'Position', [0.05 0.62 0.90 0.25], ...
    'FontSize', 10, ...
    'ForegroundColor', [0.7 0.7 0.75], ...
    'BackgroundColor', [0.11 0.12 0.15]);

modeText = uicontrol(panelMode, ...
    'Style', 'text', ...
    'String', 'STOP', ...
    'Units', 'normalized', ...
    'Position', [0.05 0.12 0.90 0.45], ...
    'FontSize', 17, ...
    'FontWeight', 'bold', ...
    'ForegroundColor', [1 0.3 0.3], ...
    'BackgroundColor', [0.11 0.12 0.15]);

%% ---------------- ADC ----------------

panelADC = uipanel(fig, ...
    'Units', 'normalized', ...
    'Position', [0.215 0.765 0.18 0.11], ...
    'BackgroundColor', [0.11 0.12 0.15]);

uicontrol(panelADC, ...
    'Style', 'text', ...
    'String', 'ADC INPUT', ...
    'Units', 'normalized', ...
    'Position', [0.05 0.62 0.90 0.25], ...
    'FontSize', 10, ...
    'ForegroundColor', [0.7 0.7 0.75], ...
    'BackgroundColor', [0.11 0.12 0.15]);

adcText = uicontrol(panelADC, ...
    'Style', 'text', ...
    'String', '0', ...
    'Units', 'normalized', ...
    'Position', [0.05 0.12 0.90 0.45], ...
    'FontSize', 18, ...
    'FontWeight', 'bold', ...
    'ForegroundColor', [0.25 0.80 1], ...
    'BackgroundColor', [0.11 0.12 0.15]);

%% ---------------- DUTY ----------------

panelDuty = uipanel(fig, ...
    'Units', 'normalized', ...
    'Position', [0.41 0.765 0.18 0.11], ...
    'BackgroundColor', [0.11 0.12 0.15]);

uicontrol(panelDuty, ...
    'Style', 'text', ...
    'String', 'PWM DUTY', ...
    'Units', 'normalized', ...
    'Position', [0.05 0.62 0.90 0.25], ...
    'FontSize', 10, ...
    'ForegroundColor', [0.7 0.7 0.75], ...
    'BackgroundColor', [0.11 0.12 0.15]);

dutyText = uicontrol(panelDuty, ...
    'Style', 'text', ...
    'String', '0.0 %', ...
    'Units', 'normalized', ...
    'Position', [0.05 0.12 0.90 0.45], ...
    'FontSize', 18, ...
    'FontWeight', 'bold', ...
    'ForegroundColor', [0.35 1.00 0.55], ...
    'BackgroundColor', [0.11 0.12 0.15]);

%% ---------------- POSITION ----------------

panelPos = uipanel(fig, ...
    'Units', 'normalized', ...
    'Position', [0.605 0.765 0.18 0.11], ...
    'BackgroundColor', [0.11 0.12 0.15]);

uicontrol(panelPos, ...
    'Style', 'text', ...
    'String', 'POSITION', ...
    'Units', 'normalized', ...
    'Position', [0.05 0.62 0.90 0.25], ...
    'FontSize', 10, ...
    'ForegroundColor', [0.7 0.7 0.75], ...
    'BackgroundColor', [0.11 0.12 0.15]);

posText = uicontrol(panelPos, ...
    'Style', 'text', ...
    'String', '0.00 deg', ...
    'Units', 'normalized', ...
    'Position', [0.05 0.12 0.90 0.45], ...
    'FontSize', 17, ...
    'FontWeight', 'bold', ...
    'ForegroundColor', [1.00 0.72 0.25], ...
    'BackgroundColor', [0.11 0.12 0.15]);

%% ---------------- RPM ----------------

panelRPM = uipanel(fig, ...
    'Units', 'normalized', ...
    'Position', [0.80 0.765 0.18 0.11], ...
    'BackgroundColor', [0.11 0.12 0.15]);

uicontrol(panelRPM, ...
    'Style', 'text', ...
    'String', 'MOTOR SPEED', ...
    'Units', 'normalized', ...
    'Position', [0.05 0.62 0.90 0.25], ...
    'FontSize', 10, ...
    'ForegroundColor', [0.7 0.7 0.75], ...
    'BackgroundColor', [0.11 0.12 0.15]);

rpmText = uicontrol(panelRPM, ...
    'Style', 'text', ...
    'String', '0.00 RPM', ...
    'Units', 'normalized', ...
    'Position', [0.05 0.12 0.90 0.45], ...
    'FontSize', 17, ...
    'FontWeight', 'bold', ...
    'ForegroundColor', [1.00 0.40 0.60], ...
    'BackgroundColor', [0.11 0.12 0.15]);

%% ============================================================
%                    NETWORK STATUS PANEL
%% ============================================================

networkPanel = uipanel(fig, ...
    'Title', ' NETWORK STATUS ', ...
    'Units', 'normalized', ...
    'Position', [0.02 0.635 0.96 0.105], ...
    'BackgroundColor', [0.09 0.10 0.13], ...
    'ForegroundColor', [0.25 0.8 1], ...
    'FontSize', 10, ...
    'FontWeight', 'bold');

%% ---------------- WIFI INDICATOR ----------------

wifiLed = uicontrol(networkPanel, ...
    'Style', 'text', ...
    'String', '●', ...
    'Units', 'normalized', ...
    'Position', [0.02 0.52 0.025 0.30], ...
    'FontSize', 17, ...
    'ForegroundColor', [1 0.3 0.3], ...
    'BackgroundColor', [0.09 0.10 0.13]);

wifiText = uicontrol(networkPanel, ...
    'Style', 'text', ...
    'String', 'WiFi: WAITING', ...
    'Units', 'normalized', ...
    'Position', [0.045 0.52 0.12 0.30], ...
    'FontSize', 9, ...
    'HorizontalAlignment', 'left', ...
    'ForegroundColor', [0.85 0.85 0.85], ...
    'BackgroundColor', [0.09 0.10 0.13]);

%% ---------------- TCP INDICATOR ----------------

tcpLed = uicontrol(networkPanel, ...
    'Style', 'text', ...
    'String', '●', ...
    'Units', 'normalized', ...
    'Position', [0.17 0.52 0.025 0.30], ...
    'FontSize', 17, ...
    'ForegroundColor', [1 0.3 0.3], ...
    'BackgroundColor', [0.09 0.10 0.13]);

tcpText = uicontrol(networkPanel, ...
    'Style', 'text', ...
    'String', 'TCP: WAITING', ...
    'Units', 'normalized', ...
    'Position', [0.195 0.52 0.11 0.30], ...
    'FontSize', 9, ...
    'HorizontalAlignment', 'left', ...
    'ForegroundColor', [0.85 0.85 0.85], ...
    'BackgroundColor', [0.09 0.10 0.13]);

%% ---------------- DATA INDICATOR ----------------

dataLed = uicontrol(networkPanel, ...
    'Style', 'text', ...
    'String', '●', ...
    'Units', 'normalized', ...
    'Position', [0.31 0.52 0.025 0.30], ...
    'FontSize', 17, ...
    'ForegroundColor', [1 0.3 0.3], ...
    'BackgroundColor', [0.09 0.10 0.13]);

dataText = uicontrol(networkPanel, ...
    'Style', 'text', ...
    'String', 'DATA: NO RX', ...
    'Units', 'normalized', ...
    'Position', [0.335 0.52 0.12 0.30], ...
    'FontSize', 9, ...
    'HorizontalAlignment', 'left', ...
    'ForegroundColor', [0.85 0.85 0.85], ...
    'BackgroundColor', [0.09 0.10 0.13]);

%% ---------------- IP INFORMATION ----------------

serverIpText = uicontrol(networkPanel, ...
    'Style', 'text', ...
    'String', sprintf('Server IP: %s', SERVER_IP), ...
    'Units', 'normalized', ...
    'Position', [0.02 0.08 0.20 0.30], ...
    'FontName', 'Consolas', ...
    'FontSize', 9, ...
    'HorizontalAlignment', 'left', ...
    'ForegroundColor', [0.70 0.85 1], ...
    'BackgroundColor', [0.09 0.10 0.13]);

portText = uicontrol(networkPanel, ...
    'Style', 'text', ...
    'String', sprintf('Port: %d', SERVER_PORT), ...
    'Units', 'normalized', ...
    'Position', [0.22 0.08 0.10 0.30], ...
    'FontName', 'Consolas', ...
    'FontSize', 9, ...
    'HorizontalAlignment', 'left', ...
    'ForegroundColor', [0.70 0.85 1], ...
    'BackgroundColor', [0.09 0.10 0.13]);

espIpText = uicontrol(networkPanel, ...
    'Style', 'text', ...
    'String', sprintf('ESP-01 IP: %s', ESP_IP), ...
    'Units', 'normalized', ...
    'Position', [0.34 0.08 0.20 0.30], ...
    'FontName', 'Consolas', ...
    'FontSize', 9, ...
    'HorizontalAlignment', 'left', ...
    'ForegroundColor', [0.70 0.85 1], ...
    'BackgroundColor', [0.09 0.10 0.13]);

packetNetworkText = uicontrol(networkPanel, ...
    'Style', 'text', ...
    'String', 'Packets: 0', ...
    'Units', 'normalized', ...
    'Position', [0.48 0.52 0.13 0.30], ...
    'FontName', 'Consolas', ...
    'FontSize', 9, ...
    'HorizontalAlignment', 'left', ...
    'ForegroundColor', [0.35 1 0.65], ...
    'BackgroundColor', [0.09 0.10 0.13]);

rateText = uicontrol(networkPanel, ...
    'Style', 'text', ...
    'String', 'RX Rate: 0.0 pkt/s', ...
    'Units', 'normalized', ...
    'Position', [0.62 0.52 0.17 0.30], ...
    'FontName', 'Consolas', ...
    'FontSize', 9, ...
    'HorizontalAlignment', 'left', ...
    'ForegroundColor', [0.35 1 0.65], ...
    'BackgroundColor', [0.09 0.10 0.13]);

lastRxText = uicontrol(networkPanel, ...
    'Style', 'text', ...
    'String', 'Last RX: --:--:--', ...
    'Units', 'normalized', ...
    'Position', [0.80 0.52 0.18 0.30], ...
    'FontName', 'Consolas', ...
    'FontSize', 9, ...
    'HorizontalAlignment', 'left', ...
    'ForegroundColor', [1 0.8 0.35], ...
    'BackgroundColor', [0.09 0.10 0.13]);

%% ============================================================
%                       GRAPH ADC
%% ============================================================

axADC = axes(fig, ...
    'Units', 'normalized', ...
    'Position', [0.065 0.365 0.40 0.22]);

hold(axADC, 'on');
grid(axADC, 'on');

adcLine = animatedline(axADC, 'LineWidth', 1.5);

title(axADC, 'ADC INPUT');
xlabel(axADC, 'Time (s)');
ylabel(axADC, 'ADC');

ylim(axADC, [0 4095]);

set(axADC, ...
    'Color', [0.09 0.10 0.13], ...
    'XColor', [0.80 0.80 0.80], ...
    'YColor', [0.80 0.80 0.80], ...
    'GridColor', [0.40 0.40 0.40]);

%% ============================================================
%                       GRAPH DUTY
%% ============================================================

axDuty = axes(fig, ...
    'Units', 'normalized', ...
    'Position', [0.555 0.365 0.40 0.22]);

hold(axDuty, 'on');
grid(axDuty, 'on');

dutyLine = animatedline(axDuty, 'LineWidth', 1.5);

title(axDuty, 'PWM DUTY CYCLE');
xlabel(axDuty, 'Time (s)');
ylabel(axDuty, 'Duty (%)');

ylim(axDuty, [0 100]);

set(axDuty, ...
    'Color', [0.09 0.10 0.13], ...
    'XColor', [0.80 0.80 0.80], ...
    'YColor', [0.80 0.80 0.80], ...
    'GridColor', [0.40 0.40 0.40]);

%% ============================================================
%                       GRAPH POSITION
%% ============================================================

axPos = axes(fig, ...
    'Units', 'normalized', ...
    'Position', [0.065 0.095 0.40 0.22]);

hold(axPos, 'on');
grid(axPos, 'on');

posLine = animatedline(axPos, 'LineWidth', 1.5);

title(axPos, 'MOTOR POSITION');
xlabel(axPos, 'Time (s)');
ylabel(axPos, 'Position (deg)');

set(axPos, ...
    'Color', [0.09 0.10 0.13], ...
    'XColor', [0.80 0.80 0.80], ...
    'YColor', [0.80 0.80 0.80], ...
    'GridColor', [0.40 0.40 0.40]);

%% ============================================================
%                       GRAPH RPM
%% ============================================================

axRPM = axes(fig, ...
    'Units', 'normalized', ...
    'Position', [0.555 0.095 0.40 0.22]);

hold(axRPM, 'on');
grid(axRPM, 'on');

rpmLine = animatedline(axRPM, 'LineWidth', 1.5);

yline(axRPM, 0, '--');

title(axRPM, 'MOTOR SPEED');
xlabel(axRPM, 'Time (s)');
ylabel(axRPM, 'RPM');

set(axRPM, ...
    'Color', [0.09 0.10 0.13], ...
    'XColor', [0.80 0.80 0.80], ...
    'YColor', [0.80 0.80 0.80], ...
    'GridColor', [0.40 0.40 0.40]);

%% ============================================================
%                       RAW DATA
%% ============================================================

rawText = uicontrol(fig, ...
    'Style', 'text', ...
    'String', 'RAW: waiting...', ...
    'Units', 'normalized', ...
    'Position', [0.02 0.015 0.96 0.035], ...
    'HorizontalAlignment', 'left', ...
    'FontName', 'Consolas', ...
    'FontSize', 9, ...
    'ForegroundColor', [0.65 0.75 0.80], ...
    'BackgroundColor', [0.06 0.07 0.09]);

drawnow;

%% ============================================================
%               WAIT FOR ESP-01 TCP CONNECTION
%% ============================================================

fprintf('=============================================\n');
fprintf(' STM32 MOTOR CONTROL TCP SERVER\n');
fprintf(' Server IP   : %s\n', SERVER_IP);
fprintf(' Server Port : %d\n', SERVER_PORT);
fprintf(' Waiting ESP-01...\n');
fprintf('=============================================\n\n');

try

    fopen(server);

catch ME

    fprintf('TCP Server Error: %s\n', ME.message);

    try
        delete(server);
    catch
    end

    if ishandle(fig)
        delete(fig);
    end

    return;

end

%% ============================================================
%                   CONNECTION SUCCESS
%% ============================================================

set(statusText, ...
    'String', sprintf( ...
    'ESP-01 CONNECTED  |  %s:%d', ...
    SERVER_IP, SERVER_PORT), ...
    'ForegroundColor', [0.30 1.00 0.45]);

set(wifiLed, ...
    'ForegroundColor', [0.25 1.00 0.35]);

set(wifiText, ...
    'String', 'WiFi: CONNECTED');

set(tcpLed, ...
    'ForegroundColor', [0.25 1.00 0.35]);

set(tcpText, ...
    'String', 'TCP: CONNECTED');

fprintf('>>> ESP-01 CONNECTED <<<\n\n');

drawnow;

%% ============================================================
%                    RECEIVE VARIABLES
%% ============================================================

buffer = '';

packetCount = 0;

startTime = tic;

lastPacketTimer = tic;

rateTimer = tic;
ratePackets = 0;
rxRate = 0;

%% ============================================================
%                       MAIN LOOP
%% ============================================================

try

    while ishandle(fig)

        %% ----------------------------------------------------
        % GUI close request
        %% ----------------------------------------------------

        if getappdata(fig, 'STOP_PROGRAM')
            break;
        end

        %% ----------------------------------------------------
        % Check TCP data
        %% ----------------------------------------------------

        nb = server.BytesAvailable;

        if nb > 0

            raw = fread(server, nb, 'uint8');

            raw = char(raw');

            buffer = [buffer raw];

            %% ------------------------------------------------
            % Tach tung packet theo \n
            %% ------------------------------------------------

            while any(buffer == char(10))

                idx = find(buffer == char(10), 1);

                line = strtrim(buffer(1:idx-1));

                buffer = buffer(idx+1:end);

                if isempty(line)
                    continue;
                end

                %% --------------------------------------------
                % RAW packet
                %% --------------------------------------------

                if ishandle(rawText)

                    set(rawText, ...
                        'String', ['RAW: ' line]);

                end

                %% --------------------------------------------
                % STM32 gui:
                %
                % Boot : Mode:0,...
                %
                % remove prefix
                %% --------------------------------------------

                line = strrep(line, 'Boot : ', '');

                %% --------------------------------------------
                % Default data
                %% --------------------------------------------

                mode_val = NaN;
                adc_val  = NaN;
                duty_val = NaN;
                pos_val  = NaN;
                rpm_val  = NaN;

                %% --------------------------------------------
                % Parse packet
                %% --------------------------------------------

                tokens = strsplit(line, ',');

                for k = 1:length(tokens)

                    kv = strsplit(tokens{k}, ':');

                    if length(kv) ~= 2
                        continue;
                    end

                    key = strtrim(kv{1});
                    val = strtrim(kv{2});

                    switch key

                        case 'Mode'

                            mode_val = str2double(val);

                        case 'ADC'

                            adc_val = str2double(val);

                        case 'Duty'

                            duty_val = str2double(val);

                        case 'Pos'

                            pos_val = str2double(val);

                        case 'RPM'

                            rpm_val = str2double(val);

                    end

                end

                %% --------------------------------------------
                % Packet validation
                %% --------------------------------------------

                if isnan(mode_val) || ...
                   isnan(adc_val)  || ...
                   isnan(duty_val) || ...
                   isnan(pos_val)  || ...
                   isnan(rpm_val)

                    continue;

                end

                %% =================================================
                %                     NEW PACKET
                %% =================================================

                packetCount = packetCount + 1;

                ratePackets = ratePackets + 1;

                lastPacketTimer = tic;

                t = toc(startTime);

                %% -------------------------------------------------
                % DATA STATUS GREEN
                %% -------------------------------------------------

                set(dataLed, ...
                    'ForegroundColor', [0.25 1.00 0.35]);

                set(dataText, ...
                    'String', 'DATA: RECEIVING');

                %% -------------------------------------------------
                % Packet count
                %% -------------------------------------------------

                set(packetNetworkText, ...
                    'String', sprintf( ...
                    'Packets: %d', ...
                    packetCount));

                %% -------------------------------------------------
                % Last receive time
                %% -------------------------------------------------

                lastRx = datestr(now, 'HH:MM:SS');

                set(lastRxText, ...
                    'String', sprintf( ...
                    'Last RX: %s', ...
                    lastRx));

                %% =================================================
                %                   RX RATE
                %% =================================================

                elapsedRate = toc(rateTimer);

                if elapsedRate >= 1.0

                    rxRate = ratePackets / elapsedRate;

                    ratePackets = 0;

                    rateTimer = tic;

                    set(rateText, ...
                        'String', sprintf( ...
                        'RX Rate: %.1f pkt/s', ...
                        rxRate));

                end

                %% =================================================
                %                 MODE STRING
                %% =================================================

                if mode_val >= 0 && mode_val <= 2

                    mode_str = ...
                        mode_names{mode_val + 1};

                else

                    mode_str = 'UNKNOWN';

                end

                %% =================================================
                %                   MODE COLOR
                %% =================================================

                switch mode_val

                    case 0

                        set(modeText, ...
                            'String', 'FORWARD', ...
                            'ForegroundColor', ...
                            [0.25 1.00 0.40]);

                    case 1

                        set(modeText, ...
                            'String', 'REVERSE', ...
                            'ForegroundColor', ...
                            [1.00 0.65 0.20]);

                    case 2

                        set(modeText, ...
                            'String', 'STOP', ...
                            'ForegroundColor', ...
                            [1.00 0.30 0.30]);

                    otherwise

                        set(modeText, ...
                            'String', 'UNKNOWN', ...
                            'ForegroundColor', ...
                            [0.80 0.80 0.80]);

                end

                %% =================================================
                %                   VALUE CARDS
                %% =================================================

                set(adcText, ...
                    'String', sprintf( ...
                    '%d', ...
                    round(adc_val)));

                set(dutyText, ...
                    'String', sprintf( ...
                    '%.1f %%', ...
                    duty_val));

                set(posText, ...
                    'String', sprintf( ...
                    '%.2f deg', ...
                    pos_val));

                set(rpmText, ...
                    'String', sprintf( ...
                    '%.2f RPM', ...
                    rpm_val));

                %% =================================================
                %                     GRAPH
                %% =================================================

                addpoints( ...
                    adcLine, ...
                    t, ...
                    adc_val);

                addpoints( ...
                    dutyLine, ...
                    t, ...
                    duty_val);

                addpoints( ...
                    posLine, ...
                    t, ...
                    pos_val);

                addpoints( ...
                    rpmLine, ...
                    t, ...
                    rpm_val);

                %% =================================================
                %                MOVING TIME WINDOW
                %% =================================================

                if t <= PLOT_WINDOW

                    xmin = 0;
                    xmax = PLOT_WINDOW;

                else

                    xmin = t - PLOT_WINDOW;
                    xmax = t;

                end

                xlim(axADC,  [xmin xmax]);
                xlim(axDuty, [xmin xmax]);
                xlim(axPos,  [xmin xmax]);
                xlim(axRPM,  [xmin xmax]);

                %% =================================================
                %              AUTO SCALE POSITION
                %% =================================================

                if abs(pos_val) < 10

                    ylim(axPos, [-10 10]);

                else

                    rangePos = max(20, abs(pos_val) * 1.20);

                    ylim(axPos, ...
                        [-rangePos rangePos]);

                end

                %% =================================================
                %                 AUTO SCALE RPM
                %% =================================================

                if abs(rpm_val) < 20

                    ylim(axRPM, [-20 20]);

                else

                    rangeRPM = max(30, ...
                        abs(rpm_val) * 1.25);

                    ylim(axRPM, ...
                        [-rangeRPM rangeRPM]);

                end

            end
        end

        %% ====================================================
        %               DATA CONNECTION WATCHDOG
        %% ====================================================

        noDataTime = toc(lastPacketTimer);

        if noDataTime > DATA_TIMEOUT

            set(dataLed, ...
                'ForegroundColor', ...
                [1.00 0.25 0.25]);

            set(dataText, ...
                'String', ...
                'DATA: LOST');

            set(statusText, ...
                'String', ...
                'ESP-01 CONNECTED | NO DATA RECEIVED', ...
                'ForegroundColor', ...
                [1.00 0.65 0.20]);

        elseif packetCount > 0

            set(statusText, ...
                'String', sprintf( ...
                'ESP-01 CONNECTED  |  %s:%d  |  RX %.1f pkt/s', ...
                SERVER_IP, ...
                SERVER_PORT, ...
                rxRate), ...
                'ForegroundColor', ...
                [0.30 1.00 0.45]);

        end

        %% ====================================================
        %       AUTO RECONNECT - mat data qua 8s thi reconnect
        %% ====================================================

        RECONNECT_TIMEOUT = 8.0;

        if noDataTime > RECONNECT_TIMEOUT

            fprintf('[%s] Data lost %.1fs - Reconnecting...\n', ...
                datestr(now, 'HH:MM:SS'), noDataTime);

            set(statusText, ...
                'String', ...
                'RECONNECTING... WAITING FOR ESP-01', ...
                'ForegroundColor', ...
                [1.00 0.75 0.20]);

            set(tcpLed, ...
                'ForegroundColor', [1 0.3 0.3]);

            set(tcpText, ...
                'String', 'TCP: RECONNECTING');

            drawnow;

            % Dong server cu
            try
                fclose(server);
            catch
            end

            pause(0.5);

            % Mo lai server cho ESP connect moi
            try
                server.Timeout = 30;
                fopen(server);

                % Thanh cong
                set(tcpLed, ...
                    'ForegroundColor', [0.25 1.00 0.35]);

                set(tcpText, ...
                    'String', 'TCP: CONNECTED');

                set(statusText, ...
                    'String', sprintf( ...
                    'ESP-01 RECONNECTED  |  %s:%d', ...
                    SERVER_IP, SERVER_PORT), ...
                    'ForegroundColor', ...
                    [0.30 1.00 0.45]);

                set(dataLed, ...
                    'ForegroundColor', [1 0.3 0.3]);

                set(dataText, ...
                    'String', 'DATA: WAITING');

                fprintf('[%s] ESP-01 Reconnected!\n', ...
                    datestr(now, 'HH:MM:SS'));

                % Reset timer va buffer
                lastPacketTimer = tic;
                rateTimer = tic;
                ratePackets = 0;
                buffer = '';

            catch ME2
                fprintf('[%s] Reconnect failed: %s\n', ...
                    datestr(now, 'HH:MM:SS'), ME2.message);

                % Thu mo lai lan nua
                try
                    fclose(server);
                catch
                end

                lastPacketTimer = tic;
            end

        end

        %% ====================================================
        %                    GUI REFRESH
        %% ====================================================

        drawnow limitrate;

        pause(0.01);

    end

catch ME

    fprintf('\nRuntime Error: %s\n', ...
        ME.message);

end

%% ============================================================
%                       CLEANUP
%% ============================================================

fprintf('\n=============================================\n');
fprintf(' Closing TCP Server...\n');

try

    if strcmp(server.Status, 'open')

        fclose(server);

    end

catch
end

try

    delete(server);

catch
end

fprintf(' Total packets received: %d\n', ...
    packetCount);

fprintf(' Server closed.\n');
fprintf('=============================================\n');

if ishandle(fig)

    delete(fig);

end